### ISSUE TITLE
[Feat] 업로드 뷰 디자인 변경사항 반영 

### ISSUE THREAD

**Issue by alpha-kwhn** [team-winey/Winey-iOS#104]
## 🛠 Issue
업로드 뷰 디자인 변경사항 반영

## 📝 To-do
- [x] 변경된 마진 적용하기
- [x] 텍스트 뷰 빨간테두리 케이스 적용
- [x] 토스트 메시지 제작
- [x] 단계 뒤로가기 누를 시에 작성 중인 내용 지워지게 하기
- [x] 뒤로 넘어갈 때 Alert 뜨게 하기
