### ISSUE TITLE
[Feat] 닉네임 설정 뷰 제작

### ISSUE THREAD

**Issue by alpha-kwhn** [team-winey/Winey-iOS#112]
## 🛠 Issue
닉네임 설정 뷰를 제작합니다

## 📝 To-do

- [x] 업로드 뷰와 겹치는 컴포넌트들 디자인 시스템에 일반화시키기
- [x] 중복버튼 디자인 시스템에 새로이 추가
- [x] 텍스트 필드 디자인 시스템에 타입 새로 추가
- [x] 닉네임 수정 뷰와 분기처리 
- [x] 로그인 로직에 뷰 적용
- [x] 뷰 완성
