### ISSUE TITLE
[Feat] 알림뷰 네트워크 구현

### ISSUE THREAD

**Issue by GodSamble** [team-winey/Winey-iOS#113]
## 🛠 Issue

알림뷰 네트워크

## 📝 To-do

- [x] 알림뷰 Get 네트워크 구현
- [x] 알림 종류에 따른 화면전환 코드 구현
- [x] 셀 알림 종류에 따른 핵심 이미지를 유동적으로 변경하게 구현
- [x] 필요한 에셋을 추가
