### ISSUE TITLE
[Feat] 닉네임 중복확인 & 수정 API 연결 및 상황별 텍스트필드 디자인 예외처리

### ISSUE THREAD

**Issue by alpha-kwhn** [team-winey/Winey-iOS#122]
## 🛠 Issue
닉네임 중복확인 버튼을 눌러서 현재 입력한 닉네임이 사용가능한 것인지를 판단합니다

## 📝 To-do
- [x] 중복확인 버튼 클릭시 현재 입력된 닉네임 데이터 가져오기
- [x] 가져온 닉네임을 바탕으로 서버 통신을 통해 중복된 닉네임인지 확인
- [x] response에 따라 알맞은 안내문구/테두리 색상을 적용
- [x] 상황별 텍스트필드 디자인 예외처리
- [x] 확인버튼 활성화 조건 설정
- [x] 확인 누르면 닉네임 업데이트 & VC dismiss되게끔 하기
