### ISSUE TITLE
[Fix] #115 이슈 브랜치 미최신화에 따른 오류 해결

### ISSUE THREAD

**Issue by alpha-kwhn** [team-winey/Winey-iOS#124]
## 🛠 Issue
#115 번 이슈 브랜치가 최신화된 develop을 바탕으로 만들어진 브랜치가 아니었던 이슈로, PR Merge 후에 코드가 꼬여버렸습니다..

## 📝 To-do
- [ ] develop 브랜치 시점 되돌리기 (#90 번 이슈 브랜치가 develop에 머지된 시점)
- [ ] 해당 시점에서 #115 번 이슈 브랜치 재생성
- [ ] #115번 이슈 브랜치에서 코드 작성후 원격에 푸쉬 & 원격 develop이랑 병합
- [ ] pull을 통해 로컬 develop 최신화
- [ ] 로컬 develop을 #112 번 이슈 브랜치로 병합
- [ ] #112번 이슈 브랜치 PR 날리기
