### ISSUE TITLE
[Feat] 피드 업로드 단계에서 네비바 버튼 클릭시 수행되는 동작 정의 및 알람 뜨는 경우 예외처리

### ISSUE THREAD

**Issue by alpha-kwhn** [team-winey/Winey-iOS#135]
## 🛠 Issue
피드 업로드 단계에서 네비바 버튼 클릭시 수행되는 동작 정의 및 알람 뜨는 경우 예외처리

## 📝 To-do
[네비바 버튼 타입에 따른 역할 분기]
- [ ] 사진 업로드 단계에서 네비바 X 버튼 누르면 VC dismiss 되게끔 하기

[알람 뷰 뜨는 예외처리]
- [ ] 첫 단계에서 이미지 갤러리에서 선택된 경우에만 알림뜨게하기
- [ ] 두 번째, 세 번째 단계에서 텍스트가 1자 이상 입력된 경우에만 알림뜨게하기
