### ISSUE TITLE
[Enhaunce] 갤러리 접근 권한 디테일 잡기

### ISSUE THREAD

**Issue by alpha-kwhn** [team-winey/Winey-iOS#139]
## 🛠 Issue
갤러리 접근 권한 디테일 잡기

## 📝 To-do
- [x] 접근 권한 허용 거부 클릭시 뜨는 Alert 배경색 검정색으로 수정하기
- [x] 접근 권한이 허용된 사진만 모여있는 CollectionView 생성하기
- [x] 접근 권한을 추가적으로 허용하고 싶은 사진들 선택하는 기능추가
- [x] 접근 권한이 추가적으로 허용된 이미지들이 선택되면, CollectionView에 이들이 즉각적으로 반영되게끔 해주기
