### ISSUE TITLE
[Fix] 알림뷰 수정 (화면전환/예외처리/함수)

### ISSUE THREAD

**Issue by GodSamble** [team-winey/Winey-iOS#141]
## 🛠 Issue

알림뷰 수정을 진행합니다.

## 📝 To-do

- [x] 화면전환 -> [좋아요] [댓글] 종류의 알림을 눌렀을 때, 상세 디테일 뷰로 넘어가도록 화면전환을 진행합니다.
- [x] configure() 수정 -> 서버로부터 넘어온 영문의 'String'을 한글 표기로 바꿉니다.
- [x] 예외처리 -> 예외처리를 진행합니다.
