### ISSUE TITLE
[Fix] 아요 자체 QA

### ISSUE THREAD

**Issue by 6uohul** [team-winey/Winey-iOS#146]
## 🛠 Issue

- 디테일 뷰 수정
- 온보딩 스킵버튼

## 📝 To-do

- [ ] 디테일 뷰 수정
- [ ] 온보딩 스킵 버튼
- [ ] 마이페이지에 온보딩 뷰 추가
- [ ] 디테일 뷰에서 삭제버튼 눌렀을 때 팝업 띄우기
