### ISSUE TITLE
[Fix] iOS 자체 QA

### ISSUE THREAD

**Issue by GodSamble** [team-winey/Winey-iOS#150]
## 🛠 Issue

아요 자체 QA를 진행합니다.

## 📝 To-do

- [x] 마이피드에서 디테일뷰로 화면전환
- [x] 마이페이지 메뉴 영역 구분선 UIView로 배치
- [x] 닉네임변경 버튼 위치 조정
