### ISSUE TITLE
[Fix] iOS 자체 QA

### ISSUE THREAD

**Issue by alpha-kwhn** [team-winey/Winey-iOS#151]
## 🛠 Issue
iOS 자체 QA

## 📝 To-do

- [ ] 닉네임 수정 뷰 전환방식 조정
- [ ] 닉네임 수정 뷰 진입 시에 원래 닉네임 나와있게
- [ ] 로그인 버튼 레이아웃 조정
