### ISSUE TITLE
[Fix] 2차 QA

### ISSUE THREAD

**Issue by GodSamble** [team-winey/Winey-iOS#158]
## 🛠 Issue

 2차 QA 피드백 받은 것들을 수정 진행합니다.

## 📝 To-do

- [x] 마이페이지 목표설정 영역 변경
- [x] 알림뷰 스크롤 시 새로고침 기능추가
- [x] 마이페이지 메뉴 항목 간에 폰트차이로 인한 문제 코드 수정
- [x] 메뉴 하단쏠림조정
- [x] 목표설정 하단쏠림조정
- [x] D - - day 텍스트 수정

**Comment by alpha-kwhn** [comment]
저거 하나만 할꺼 아니죠 설마? ㅎㅎㅎㅎ
