### ISSUE TITLE
[Fix] 디자인 수정사항 반영 & 닉네임 설정 뷰 디자인 오류 수정

### ISSUE THREAD

**Issue by alpha-kwhn** [team-winey/Winey-iOS#164]
## 🛠 Issue
디자인 수정사항 반영 & 닉네임 설정 뷰 디자인 오류 수정

## 📝 To-do

- [x] 사진 업로드 썸네일 박스 크기 조정
- [x] 닉네임 수정으로 이동했을때 글자수 반영시키기
- [x] 새로 제공받은 프로필 이미지 Asset 튕김 현상 수정
