### ISSUE TITLE
[Feat] 선택된 사진만 접근 가능 예외처리

### ISSUE THREAD

**Issue by alpha-kwhn** [team-winey/Winey-iOS#166]
## 🛠 Issue
선택된 사진만 접근 가능 예외처리 및 갤러리 로직 설계 & 잔버그 수정

## 📝 To-do

1) .limited (선택된 사진만 접근 가능)

- [x] 갤러리 뷰에 진입할 때 '접근권한 허용 이미지 추가 or 유지'를 물어보는 Custom Alert이 뜨도록 설정
- [x] 알림에서 접근권한 이미지 추가를 눌렀을 때 LimitedLibraryPicker가 나타나서 고를 수 있게끔 설정
- [x] PHPhotoLibraryChangeObserver를 적용하여, LimitedLibraryPicker에서 선택된 이미지 들에 변경사항이 있을 경우 즉각 대응할 수 있도록 처리
- [x] 여러 타입의 갤러리들을 포함할 수 있는 collectionView를 GalleryViewController에 제작하여 추가
- [x] collectionView에 보여질 셀 디자인
- [x] 셀에 보여질 썸네일 이미지 설정
- [x] 셀에 보여질 접근 권한 허용된 이미지 개수 설정
- [x] 갤러리 collectionView cell을 눌러 진입하면 보여지는 ImagePicker 뷰 제작
- [x] 접근권한 이미지를 캐싱하고 가져오는 로직 설계를 통한 성능 향상
- [x] 원본 사이즈를 기준으로 고화질의 이미지가 선택되어 피드에 잘 업로드 되는지 확인
- [x] 설정 창으로 나가서, 별도로 접근 권한 가능 사진 편집하고 앱에 진입할 경우 -> 수정사항 즉각 반영되도록 예외처리

2) .denied (접근권한 없음)

- [x] alert가 안뜨는 버그 수정
