### ISSUE TITLE
[Fix] 피드백 반영

### ISSUE THREAD

**Issue by alpha-kwhn** [team-winey/Winey-iOS#169]
## 🛠 Issue
테플 기반 피드백 반영

## 📝 To-do

- [x] 피드 디테일 뷰 순대 버튼 통일
- [x] 이미지 피커 체크버튼 없애기
- [x] 전으로 스와이프 되도록 구현
- [x] 온보딩 하단 background색 변경
