### ISSUE TITLE
[Fix] 디자인 QA + 사진 저화질 이슈 수정

### ISSUE THREAD

**Issue by alpha-kwhn** [team-winey/Winey-iOS#173]
## 🛠 Issue
디자인 QA + 사진 저화질 이슈 수정

## 📝 To-do
- [x] 닉네임 수정뷰 네비바 버튼 이미지 교체
- [x] 닉네임 수정 플로우 디자인 QA 반영하여 수정
- [x] 사진 저화질로 안올라오게 막아보기
