### ISSUE TITLE
[Fix] 최종점검

### ISSUE THREAD

**Issue by alpha-kwhn** [team-winey/Winey-iOS#193]
## 🛠 Issue
닉네임 입력 텍스트필드 하단 문구 로직이 조금 꼬여있음

## 📝 To-do
- [x] 하단 문구 출력 로직 손보기
- [x] 닉네임 수정 로직 손보기
- [x] 리프레쉬 토큰 만료 시에 앱이 Back->Foreground로 넘어올 때 윈도우 VC 설정해주기
- [x] 링크 없는 추천절약법 필터링
- [x] URL에 한글 포함된 경우에도 인코딩되도록 처리
- [x] 천지인 자판 .인식 안됨 오류 해결
