### ISSUE TITLE
[Feat] [Bug] 새로운 배너 추가 / 첫 목표 설정 팝업 스펙 수정 / 스크롤 버그 수정 (탭클릭, 간헐적 스크롤 위치)

### ISSUE THREAD

**Issue by samsung-ga** [team-winey/Winey-iOS#197]
## 🛠 Issue

제목과 동일한 작업들을 진행합니다. 

## 📝 To-do

- [x] 새로운 배너 추가
- [x] 첫 목표 설정 팝업 스펙 수정 
- [x] 스크롤 버그 수정
