### ISSUE TITLE
[Fix] 마이페이지 뷰 수정

### ISSUE THREAD

**Issue by GodSamble** [team-winey/Winey-iOS#29]
## 🛠 Issue

마이페이지 뷰를 수정합니다.

## 📝 To-do

- [x] 아이템 셀 간격 조정
- [x] 따봉 버튼 지우기
- [x] pen Assets 추가
- [x] 버튼 클릭허용 범위 수정
- [x] info버튼 그림자 지우기
- [x] Label 밑줄 Extension 추가
- [x] 마이페이지 (상단 스크롤 시 : 흰배경, 하단 스크롤 시 : 회색배경)
- [x] 마크주석 추가
- [x] 탭바 붙이기
