### ISSUE TITLE
[Feat] 데모데이를 위한 작업들 

### ISSUE THREAD

**Issue by samsung-ga** [team-winey/Winey-iOS#62]
## 🛠 Issue

데모데이 전, 테스트플라이트를 올리기전 필요한 사소한 작업들을 진행합니다.

## 📝 To-do

- [ ] 스플래시, 로고, 다크모드 제한, 가로모드 제한
- [ ] UserDefault에 유저 아이디 변경할 수 있는 개발자 모드 개발하기
- [ ] 마이피드 EmptyView
- [ ] 마이페이지 EmptyView → 목표가 없을때
