### ISSUE TITLE
[FIx] QA 피드백 반영

### ISSUE THREAD

**Issue by 6uohul** [team-winey/Winey-iOS#63]
## 🛠 Issue

- 내 피드, 전체 피드 삭제 및 신고 분기처리
- 추천 탭 셀 간격, 사이즈 비교
- 좋아요 버튼 이미지 수정
- 가이드 뷰 back button 터치 이벤트 추가

## 📝 To-do

- [x] 플로팅 버튼 그림자
- [x] 내 피드, 전체 피드 삭제 및 신고 분기처리
- [ ] 추천 탭 셀 간격, 사이즈 비교
- [x] 좋아요 버튼 이미지 수정
- [x] 가이드 뷰 back button 터치 이벤트 추가
