### ISSUE TITLE
[Enhanuce] 사용성 개선 

### ISSUE THREAD

**Issue by samsung-ga** [team-winey/Winey-iOS#75]
## 📝 To-do

- [x] 리프레시
- [x] 좋아요 이미지 수정 
- [x] 스플래시 변경
- [x] 탭바 누르면 위로 올라가기
- [x] 짜잘한 디자인 수정
