### ISSUE TITLE
[Feat] 디자인시스템 모듈 추가 

### ISSUE THREAD

**Issue by samsung-ga** [team-winey/Winey-iOS#9]
## 🛠 Issue

디자인시스템 모듈을 새로 생성하고 SnapKit 디펜던시를 추가합니다.
Winey 프로젝트에 정의되어있는 폰트 / 색상 / 에셋 관련 코드들을 디자인시스템 모듈로 이동시키고, 변경된 번들에 대해 정의 방식을 수정합니다. 
변경된 방식에 따라 Winey 프로젝트에 대응해줍니다. 

## 📝 To-do
- [x] 디자인시스템 모듈 생성 및 SnapKit 디펜던시 추가
- [x] 색상 코드 이전 및 대응
- [x] 에셋 코드 이전 및 대응
- [ ] 폰트 코드 이전 및 대응
- [ ] 사용법에 관해 팀원들에게 공유 및 접근지정자에 관해 설명
